#!/bin/sh /etc/rc.common
# Copyright (C) 2015 CZ.NIC z.s.p.o. (http://www.nic.cz/)

START=99
STOP=0

USE_PROCD=1
SCRIPT="/usr/bin/tv-sharp"

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/lua "$SCRIPT"
	# procd_set_param stdout 1
	# procd_set_param stderr 1
	procd_close_instance
}
